#pragma once

#include "LandingScreen/LandingScreen.h"
#include "RegisterScreen/RegisterScreen.h"
#include "OverviewScreen/OverviewScreen.h"
#include "LoginScreen/LoginScreen.h"
#include "SettingsScreen/SettingsScreen.h"
#include "OrganizationsScreen/OrganizatonsScreen.h"
#include "CoursesScreen/CoursesScreen.h"
#include "CreateCourseScreen/CreateCourseScreen.h"
#include "JoinCourseScreen/JoinCourseScreen.h"
#include "ThemesScreen/ThemesScreen.h"
#include "NewThemeScreen/NewThemeScreen.h"
#include "NewExamScreen/NewExamScreen.h"
#include "AddTestQuestionsScreen/AddTestQuestionsScreen.h"
#include "EditTestQuestionsScreen/EditTestQuestionScreen.h"
#include "AttemptTestScreen/AttemptTestScreen.h"