name: Build and deploy go app to Azure Web App - api-starcrown

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1.3

    - name: Install dependencies
      run: | 
        apt-get update
        apt-get install -y cmake
        apt-get install -y python3
        apt-get install -y libxslt-dev libxml2-dev libpam-dev libedit-dev libssl-dev

    - name: Generate premake
      run: |
        chmod +x vendor/premake/premake5
        cd server
        ./../vendor/premake/premake5 gmake

    - name: Build
      run: |
        cd server
        make
      
    - name: Zip artifact for deployment
      run: zip server/release.zip ./* -r

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: server
        path: server/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: server

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'lorem-ipsum'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
